

# Use as base image
FROM golang:latest as builder

LABEL maintainer="Markus Sagen <Markus.John.Sage@gmail.com>"

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main .



# Start new stage
FROM alpine:latest

RUN apk --no-cache add ca-certificates

WORKDIR /root/

# Copy pre-build binary from prev. stage
COPY --from=builder /app/main .

# Expose port
EXPOSE 8000

CMD ["./main"]

